docker/bin/docker-entrypoint.sh
=> Fix media & static folders setup

tests/test_commands.py
=> chg ! test upgrade init without sync with HOPE

tests/extras/testutils/factories/individual.py
=> chg ! uniquify name in IndividualFactory

src/country_workspace/management/commands/upgrade.py, tests/test_commands.py
=> chg ! by default command 'upgrade' do not run sync with HOPE

src/country_workspace/admin/__init__.py, src/country_workspace/admin/constance.py, src/country_workspace/config/fragments/constance.py
=> add ! mask display of constance default values if need.

docs/src/.pages, docs/src/data_cleaning_updates.md, docs/src/index.md, src/country_workspace/config/fragments/constance.py, src/country_workspace/workspaces/admin/cleaners/actions.py, src/country_workspace/workspaces/admin/cleaners/bulk_update.py, src/country_workspace/workspaces/admin/forms.py, src/country_workspace/workspaces/admin/program.py, src/country_workspace/workspaces/templates/workspace/actions/bulk_update_import.html, src/country_workspace/workspaces/validators.py, tests/workspace/actions/stub.py, tests/workspace/actions/test_ws_bulk.py, tests/workspace/cleaners/test_bulk_update.py
=> chg ! bulk records update

src/country_workspace/admin/beneficiary_group.py, src/country_workspace/admin/program.py, src/country_workspace/management/commands/demo.py, src/country_workspace/workspaces/admin/hh_ind.py, src/country_workspace/workspaces/admin/household.py, src/country_workspace/workspaces/admin/individual.py, src/country_workspace/workspaces/admin/program.py, src/country_workspace/workspaces/options.py, src/country_workspace/workspaces/templates/workspace/admin_extra_buttons/includes/button.html, src/country_workspace/workspaces/templates/workspace/admin_extra_buttons/includes/change_form_buttons.html, src/country_workspace/workspaces/templates/workspace/household/change_form.html, src/country_workspace/workspaces/templates/workspace/household/change_list.html, src/country_workspace/workspaces/templates/workspace/household/raw_data.html, src/country_workspace/workspaces/templates/workspace/individual/change_form.html, src/country_workspace/workspaces/templates/workspace/individual/change_list.html, src/country_workspace/workspaces/templates/workspace/individual/raw_data.html, src/country_workspace/workspaces/templates/workspace/raw_data.html, src/country_workspace/workspaces/templatetags/workspace_validation.py, tests/extras/testutils/factories/individual.py, tests/workspace/test_ws_program.py
=> AB#241769: chg ! labels according to beneficiary group

src/country_workspace/contrib/aurora/forms.py, src/country_workspace/contrib/aurora/pipeline.py, src/country_workspace/utils/fields.py, src/country_workspace/workspaces/admin/program.py, tests/contrib/aurora/stub.py, tests/workspace/test_ws_import.py
=> AB#241769: aurora import according to use beneficiary groups

src/country_workspace/config/fragments/csp.py
=> AB#241776: Flex Field override validation is not working

src/country_workspace/config/fragments/csp.py
=> AB#241776: Flex Field override validation is not working (connect src)

src/country_workspace/contrib/hope/client.py, src/country_workspace/contrib/hope/constants.py, src/country_workspace/contrib/hope/push.py, src/country_workspace/models/program.py, src/country_workspace/utils/fields.py, src/country_workspace/versioning/checkers.py, src/country_workspace/versioning/hope_fields.py, src/country_workspace/workspaces/admin/cleaners/actions.py, src/country_workspace/workspaces/admin/hh_ind.py, src/country_workspace/workspaces/admin/household.py, src/country_workspace/workspaces/admin/program.py, src/country_workspace/workspaces/sites.py, src/country_workspace/workspaces/templates/workspace/includes/fieldset.html, src/country_workspace/workspaces/templatetags/workspace_collections.py, tests/contrib/hope/test_hope_client.py, tests/contrib/hope/test_push_to_hope_core.py, tests/utils/test_utils_fields.py
=> AB#243944: push to hope core according to beneficiary groups

docs/src/import_data/kobo.md
=> AB#240798: Create import from kobo documentation

pyproject.toml, src/country_workspace/config/__init__.py, src/country_workspace/config/fragments/constance.py, src/country_workspace/config/fragments/mail.py, src/country_workspace/config/settings.py, tests/test_mail_configuration.py, uv.lock
=> AB#240865: Setup Mailjet

src/country_workspace/workspaces/admin/cleaners/bulk_update.py
=> Fix email sending issues

src/country_workspace/contrib/aurora/exceptions.py, src/country_workspace/contrib/aurora/pipeline.py, src/country_workspace/datasources/rdi.py, src/country_workspace/utils/config.py, src/country_workspace/utils/types.py, src/country_workspace/validators/beneficiaries.py, src/country_workspace/workspaces/admin/program.py, src/country_workspace/workspaces/exceptions.py, tests/contrib/aurora/stub.py, tests/datasources/test_rdi.py, tests/workspace/test_ws_import.py
[AB#246554](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/246554)
=> add ! process check-before and fail-if-alien in Aurora import

src/country_workspace/config/celery.py
=> AB#239780: Pass backend option on Celery app creation

src/country_workspace/admin/__init__.py, src/country_workspace/admin/base.py, src/country_workspace/admin/locations.py, src/country_workspace/admin/office.py, src/country_workspace/admin/program.py, src/country_workspace/admin/sync.py, src/country_workspace/admin/sync_log.py, src/country_workspace/contrib/hope/sync/context_geo.py, src/country_workspace/migrations/0012_country_hope_id.py, src/country_workspace/models/locations.py, tests/admin/test_admin_sync.py
[AB#247946](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/247946)
=> add ! sync countries through admin panel

src/country_workspace/admin/locations.py, src/country_workspace/contrib/hope/geo.py, src/country_workspace/contrib/hope/sync/context_geo.py, src/country_workspace/migrations/0013_country_iso_code3.py, src/country_workspace/models/locations.py, tests/contrib/hope/test_geo.py
[AB#248007](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/248007)
=> CountryChoice Field should work with isocode2 and isocode3

src/country_workspace/versioning/hope_fields.py, src/country_workspace/versioning/scripts/0005_fix_individual_fields_definitions.py
[AB#247958](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/247958)
=> fix ! values 'disabled' or 'not disabled' is giving an issue at validation

src/country_workspace/workspaces/admin/cleaners/mass_update.py
[AB#247947](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/247947)
=> AB#247947: mass update is not working for booleans

src/country_workspace/workspaces/admin/hh_ind.py, src/country_workspace/workspaces/static/workspace/js/select-all.js, src/country_workspace/workspaces/templates/workspace/actions/bulk_update_export.html
[AB#247252](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/247252)
=> AB#247252: Export Fields have ability to check all

src/country_workspace/datasources/rdi.py, src/country_workspace/workspaces/admin/forms.py, tests/datasources/test_rdi.py, tests/workspace/test_ws_import.py
[AB#248006](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/248006)
=> AB#248006: Import Data RDI Detail column label not working

src/country_workspace/admin/locations.py, src/country_workspace/admin/sync.py, src/country_workspace/contrib/aurora/admin/project.py, src/country_workspace/contrib/hope/geo.py, src/country_workspace/contrib/hope/sync/base.py, src/country_workspace/contrib/hope/sync/context_geo.py, src/country_workspace/contrib/hope/sync/context_programs.py, src/country_workspace/versioning/checkers.py, src/country_workspace/versioning/scripts/0006_chg_adminx_flexfields.py, tests/admin/test_admin_sync.py, tests/contrib/hope/conftest.py, tests/contrib/hope/test_context_geo.py, tests/contrib/hope/test_context_programs.py, tests/contrib/hope/test_geo.py, tests/contrib/hope/test_sync_base.py, tests/workspace/actions/test_ws_mass_update.py
[AB#242081](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/242081)
=> Synchronize Admin Area and Admin Area Type

src/country_workspace/contrib/hope/sync/context_geo.py, src/country_workspace/contrib/hope/sync/context_programs.py, tests/contrib/hope/conftest.py, tests/contrib/hope/test_context_geo.py
[AB#242081](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/242081)
=> chg ! fetch countries and offices by updated_at

src/country_workspace/workspaces/forms.py
[AB#248879](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/248879)
=> AB#248879: UserRole permission

.github/workflows/test.yml, pyproject.toml, tests/conftest.py, tests/extras/testutils/selenium.py, tests/functional/conftest.py, tests/functional/test_f_household.py, tests/functional/test_f_login.py, uv.lock
=> Setup seleniumbase

src/country_workspace/datasources/rdi.py, src/country_workspace/datasources/utils.py, tests/datasources/test_rdi.py
[AB#247955](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/247955)
=> postprocess cell when import from .xls

src/country_workspace/versioning/scripts/0007_consent_sharing.py
[AB#247967](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/247967)
=> AB#247967: consent and consent sharing

src/country_workspace/utils/flex_fields.py, tests/utils/test_utils_fields.py
[AB#252961](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/252961)
=> AB#252961: In Individuals if image wasn't changed when press Save - raised an error

tests/conftest.py, tests/functional/test_f_household.py, tests/functional/test_f_import_data.py
=> Add selenium test for select-all.js

src/country_workspace/admin/__init__.py, src/country_workspace/config/fragments/app.py, src/country_workspace/management/commands/sync.py, src/country_workspace/models/sync.py, src/country_workspace/utils/fields.py, src/country_workspace/utils/flex_fields.py, src/country_workspace/versioning/hope_fields.py, src/country_workspace/versioning/scripts/0004_add_base64_image_field.py, src/country_workspace/versioning/scripts/0007_consent_sharing.py, src/country_workspace/versioning/scripts/0008_fix_fields_per_HOPE_requirements.py, tests/models/test_m_sync_log.py, tests/test_commands.py, tests/utils/test_utils_fields.py
[AB#248880](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/248880)
=> chg ! adjust handling of HOPE fields

src/country_workspace/models/role.py, tests/models/test_role.py
[AB#247635](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/247635)
=> AB#247635: Check program matches office for UserRole

.github/actions/checksum/action.yml, .github/actions/docker_build/action.yml, docker/Dockerfile, pyproject.toml, src/country_workspace/workspaces/templatetags/workspace_urls.py, tests/admin/test_admin_smoke.py, tox.ini, uv.lock
=> dj52 py313

tests/functional/test_f_household.py
=> Add tests for export generation of households and individuals

src/country_workspace/admin/sync_log.py, src/country_workspace/utils/flex_fields.py, tests/utils/test_utils_fields.py
[AB#248880](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/248880)
=> fix ! push consent_sharing as list instead of str

src/country_workspace/workspaces/admin/program.py, tests/workspace/admin/test_program.py
[AB#248011](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/248011)
=> AB#248011: Kobo Import description

tests/functional/test_f_household.py
=> Add tests for cl.js and program.js

tests/functional/test_f_rdi_import.py
=> test rdi import scenario

tests/cache/test_cachable.py, tests/cache/test_middleware.py, tests/workspace/test_ws_sync.py, tests/workspaces/admin/test_admin_job.py, tests/workspaces/admin/test_filters.py, tests/workspaces/admin/test_program.py
=> Increase test coverage

src/country_workspace/contrib/kobo/sync.py, src/country_workspace/utils/fields.py, tests/contrib/kobo/test_kobo_sync.py
[AB#254923](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/254923)
=> AB#254923: Importing From Kobo – Primary and Alternate Collector

src/country_workspace/workspaces/admin/filters.py, src/country_workspace/workspaces/admin/household.py, src/country_workspace/workspaces/admin/individual.py, src/country_workspace/workspaces/templates/workspace/adminfilters/value_multi.html, tests/workspace/admin/test_filters.py
=> Add multivalue filter for id field to the hh and ind

src/country_workspace/contrib/aurora/pipeline.py, src/country_workspace/models/household.py, tests/contrib/hope/test_h_validators.py, tests/functional/integration/test_hope_push_lax.py
[AB#256583](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/256583) fix beneficiary validator
=> fix beneficiary validator

src/country_workspace/versioning/scripts/0009_add_document_and_account_fieldsets.py, tests/functional/test_f_import_data.py
=> Modify fields in document and account fieldsets

src/country_workspace/utils/fields.py, src/country_workspace/utils/flex_fields.py, tests/utils/test_utils_fields.py
[AB#261280](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/261280)
=> AB#261280: Consent sharing now working properly

src/country_workspace/contrib/hope/geo.py, src/country_workspace/contrib/hope/push.py, src/country_workspace/utils/fields.py, tests/contrib/hope/test_geo.py, tests/utils/test_utils_fields.py
[AB#263268](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/263268)
=> use p_code instead of UUID for admin area HOPE core API push

src/country_workspace/workspaces/admin/cleaners/bulk_update.py
[AB#263918](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/263918)
=> fix ! format values for XLSX export: lists/tuples as comma-separated

src/country_workspace/workspaces/admin/cleaners/bulk_update.py, tests/workspace/cleaners/test_bulk_update.py
https://dev.azure.com/unicef/ICTD-HCT-MIS/_workitems/edit/265163
=> Fix date and datetime object validation on bulk update

src/country_workspace/workspaces/admin/cleaners/validate.py
https://dev.azure.com/unicef/ICTD-HCT-MIS/_workitems/edit/272501
=> Fix validation issue for reference fields

src/country_workspace/workspaces/admin/hh_ind.py
https://dev.azure.com/unicef/ICTD-HCT-MIS/_workitems/edit/272939
=> Remove program name from async job description

src/country_workspace/contrib/kobo/api/client/helpers.py, tests/contrib/kobo/api/client/test_client_helpers.py
=> Hotfix: Apply explicit pagination

src/country_workspace/config/fragments/celery.py
=> Bugfix: Make Celery visibility timeout configurable
